version: '3.8'
services:
  movies:
    image: shaikhzameer/paytmmoviesrepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: shaikhzameer/paytmtrainrepo:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: shaikhzameer/paytmdthrepo:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: shaikhzameer/paytmrechargerepo:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

